### PR TITLE
Fix String attribute encoding delimiter

### LINKED ISSUE #165: ArrayIndexOutOfBounds when encoding String attributes
```java
java.lang.ArrayIndexOutOfBoundsException: 109
	at org.apollo.game.model.entity.attr.AttributeType.valueOf(AttributeType.java:43)
	at org.apollo.game.io.player.BinaryPlayerSerializer.readAttributes(BinaryPlayerSerializer.java:268)
	at org.apollo.game.io.player.BinaryPlayerSerializer.loadPlayer(BinaryPlayerSerializer.java:163)
	at org.apollo.game.login.PlayerLoaderWorker.run(PlayerLoaderWorker.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by ryleykimmel**
This resolves #165

### CODE REVIEW

**Comment by Major-** [comment]
Nice that was a real noob mistake on my part...

Please add a unit test for this

**Comment by ryleykimmel** [comment]
When writing unit tests I came across another bug (ClassCastException for ```int``` types) which this PR also addresses.

Also I have added another method in AttributeDefinition for Longs (only int was supported yet the attribute type was named long. Was this intentional?)

**Comment by Major-** [comment]
Can you `s/test//` to make the unit test names fit with the rest of them (e.g. `intEncode`).

Otherwise LGTM

**Comment by garyttierney** [comment]
>Can you s/test// to make the unit test names fit with the rest of them (e.g. intEncode).

Are you referring to the rest of the tests we have? Test cases with a naming of test<ThingUnderTest> seem to make up the majority of our unit tests. Might be worth fixing them all together.

See:

1. https://github.com/apollo-rsps/apollo/blob/master/util/src/test/org/apollo/util/TextUtilTests.java
2. https://github.com/apollo-rsps/apollo/blob/master/game/src/test/org/apollo/game/model/entity/MobRepositoryTest.java
3. https://github.com/apollo-rsps/apollo/blob/master/net/src/test/org/apollo/net/codec/game/TestGamePacketEncoder.java
4. https://github.com/apollo-rsps/apollo/blob/master/game/src/test/org/apollo/game/model/TestPosition.java

**Comment by Major-** [comment]
Ah yeah you're right, looks like it's just the [ones in util](https://github.com/apollo-rsps/apollo/tree/master/util/src/test/org/apollo/util) that don't. I personally prefer not having `test` in the method name unless necessary (e.g. `testClass`, `testDouble`) but don't mind too much.

**Comment by ryleykimmel** [comment]
See PR #171

**Comment by ryleykimmel** [comment]
Good to squash and merge?

**Pull request merged**
