### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by CharlesVaneenoo**
Hello,
I create the file "CONTRIBUTING.md", it's the first version and it will be improve in the future. 
(Issue #255)
Thanks.

### CODE REVIEW

**Comment by Major-** [comment]
Looks like a pretty good start to me, any additional thoughts @garyttierney @ryleykimmel?

**Comment by garyttierney** [comment]
@Major- have some changes I want to add. Going to pull this branch and make them.

**Comment by WizardJesse1** [comment]
wow i really like this thanks :)

**Comment by garyttierney** [comment]
Closed, duplicate of #269

**Pull request closed without merging**
