### PR TITLE
Added smithing plugin.

### PR DESCRIPTION
**Pull request by tlf30**
So this plugin is really rough. I wrote is sometime last year, and was going to clean it up and have not found the time to do so. If someone would like to work on it, feel free.

### CODE REVIEW

**Comment by tlf30** [comment]
I thought I would just clarify, this plugin is in working order, the code may be a bit messy, but it is fully functional.

**Comment by garyttierney** [comment]
@tlf30 sorry for the delay. Are you still looking for a review on this PR? I'm looking to get it closed off and can provide review feedback or pick it up myself.

**Comment by tlf30** [comment]
Hello @garyttierney I will be at work in the artic circle for the next three weeks. If you or someone wants to tackle cleaning it up, it would be much appreciated.

**Comment by Major-** [comment]
This has some useful stuff in but isn't in a good state to merge. I'm going to close this PR and when we look to add smithing we can work off this.

Thanks!

**Pull request closed without merging**
