### PR TITLE
Teleportation using the ::tele command

### PR DESCRIPTION
**Pull request by cfoust**
Lets you do `::tele [location name]` to jump there.

It's my first time using Kotlin. Please let me know any stylistic concerns you may have.

Imgur

### CODE REVIEW

**Comment by Promises** [comment]
offtopic:
Is that the client from my repo?, did i seriously forget to remove my name from default :O

**Comment by cfoust** [comment]
@Promises Hahaha yes, it is! I forked it privately so I could hack on it but just left that in

**Comment by Major-** [comment]
Excellent, LGTM

**Comment by Major-** [comment]
Merged in f6a45f8.

**Comment by Major-** [comment]
Merged in 3c6d251.

**Pull request closed without merging**
