### PR TITLE
Adding tests to Skillset.java

### PR DESCRIPTION
**Pull request by munggs**
Hello,

I created some tests for a few methods of Skillset.java. The only methods that aren't tested are really simple so they didn't need any tests.

### CODE REVIEW

**Comment by Major-** [comment]
Looks pretty good, thanks for contributing. Just a couple of nitpicks:

- Please make sure there is always a single space before open braces (`{`), and also a single space after commas (`,`)
- Please make the class `final`.
- Please rename the `skillset` variables to `skillSet`, to follow Java's camelCase convention for variables.
- Please use the constants in `Skill` instead of raw integer values (so `skillSet.getSkill(Skill.ATTACK)` instead of `skillSet.getSkill(0)`.

**Comment by munggs** [comment]
All right, It should be ok now.

Thanks

**Comment by garyttierney** [comment]
LGTM

**Comment by garyttierney** [comment]
Could do with refactoring out the repeated calls to getSkill(), actually.

**Comment by Major-** [comment]
@garyttierney `Skill`s are immutable so most of them can't be removed. I think this is good to go as-is

**Comment by garyttierney** [comment]
@Major- ah, thought that might have been the case. Looks good then.

@munggs could you fix the commit message of this PR? Please write the summary in the imperative, i.e., "Add unit tests for SkillSet" and drop the 3 repeated messages in the summary ("fixing SkillSet's tests").

**Comment by munggs** [comment]
@garyttierney I fixed the commit message and removed the repeated messages as you asked.

**Comment by munggs** [comment]
I updated the branch.
@Major-  Do you see something else that I should fix about this PR ?

**Comment by garyttierney** [comment]
Looks good. The commit you've made to this PR is a big improvement. See "The seven rules of a great git commit message" http://chris.beams.io/posts/git-commit/

**Comment by Major-** [comment]
(Just want to extend gary's comment by saying that your current git commit message is excellent, and exactly how I would have written it)

**Pull request merged**
