### PR TITLE
Add support for combat

### PR DESCRIPTION
**Pull request by garyttierney**
:warning: not ready for pulling or code review, still cherry picking :warning:

### CODE REVIEW

**Comment by garyttierney** [comment]
ping @ryleykimmel @Major- could you look at widget related code and see if there's any discrepancies from my newer revision?

**Comment by garyttierney** [comment]
latest changes need rebased and edited, blocked on projectiles

**Comment by Major-** [comment]
Woohoo!

**Comment by Major-** [comment]
Started reading through this but lots of the stuff I was finding is stuff that will rubocop will find - can you run rubocop through on this

**Comment by garyttierney** [comment]
```
commit 1ef12687c5ef6d78487ae266e045926f70357f6a
Author: Gary Tierney <gary.tierney@gmx.com>
Date:   Fri Jan 29 22:42:03 2016 +0000

    Add more documentation and fix rubocop warnings
```

>I didn't read the big warning!

**Comment by Major-** [comment]
Now Projectile support exists, is this still blocked?

**Comment by garyttierney** [comment]
Not blocked by but probably good to merge #222 first

**Comment by garyttierney** [comment]
s/merge/finish

**Comment by nstroupr** [comment]
'org.apollo.game.model.entity.AnimationSet' is missing.
'spellbook.rb' needs to be removed from 'plugin.xml'.

**Comment by garyttierney** [comment]
@nstroupr thanks, the whole tree needs rebased so each commit builds and runs.

**Comment by garyttierney** [comment]
>< Hzn> [02:42:22] sfix, what is blocking upstream-combat branch from merging? (or why you can't rebase it so it includes all the commits (with correct plugin.xml, and the required imports)?

This feature was developed against a fork of Apollo which was somewhat incompatible with upstream.

**Comment by garyttierney** [comment]
This tree is in a pretty sorry state given the rebasing and cherry picking it's went through, so I'm going to squash the WIP into a single commit and push that when I'm done cleaning it up. Then, I'll create a new todo list.

**Pull request closed without merging**
