### PR TITLE
Recipes and Skill Menus

### PR DESCRIPTION
**Pull request by shamonj03**
Review it see how you like it. Good examples are the cooking, herb, and fletching scripts. I don't have much time to finish stuff at the moment, so this is just an alpha release I guess. I guess I uploaded some files that weren't really changed/needed to be deleted. Runecrafting had errors, but this system can be used to rewrite it. Speaking of runecrafting...I guess the rewards need a proc for it as well.

I should explain what this does.
Creation of recipes for item on item (fletching), item on object (cooking/runecrafing), and item option messages (herbs). Recipes are basically requirements and rewards. If requirements met, then assign rewards. Recipes can have multiple materials required to create something and produce a product. They have skill requirements, material requirements, object requirements, and tool requirements. If there happens to be an object requirement it is an item on object event. For single item recipes there is a special main ingredient requirement. For an example of a lot of the features look at the cooking plugin.

Also created a skill menu system that allows you to add items to a skill menu for a specific tab. If that tab is not there it gets created. For recipes the product created is registered to a skill tab. You must explicitly state it's skill and the tab it will be registered to. Also to register it it must be called after the product and skill requirements have been defined.

### CODE REVIEW

**Comment by WizardJesse1** [comment]
it looks like you are trying to go back a few updates from looking at shops and etc.. did you not update your source to the current? @shamonj03

**Comment by shamonj03** [comment]
Uh. It's a couple weeks old.

**Comment by shamonj03** [comment]
I don't like my recipe class. It turned into a cluster fuck.

**Comment by WizardJesse1** [comment]
So confused what's going on

**Comment by shamonj03** [comment]
Just delete this

**Comment by ryleykimmel** [comment]
I actually really like the idea you have here.

**Comment by Major-** [comment]
Yeah I think this shows a lot of promise. Do you need a hand with git?

**Pull request closed without merging**
