### PR TITLE
refactor method handle in EquipItemHandler.java

### PR DESCRIPTION
**Pull request by pheq**
Hello,
We refactored the method handle in EquipItemHandler.java for better visibility.
To do that we extracted the case when the equipment is defined as two handed and created a method handleTwoHanded for that.
Thanks

### CODE REVIEW

**Comment by pheq** [comment]
I did the modifications you asked

**Comment by Major-** [comment]
Great, thanks. Just two more things:

- The whitespace around the commas after the parameters of the method you added is very inconsistent - it should be like `Inventory inventory, Inventory equipment, int inventorySlot, ` etc.
- The method documentation is inconsistent with other parts of apollo. I suggest changing it to:

```java
	/**
	 * Attempts to equip the two-handed item requested by the {@link Player}.
	 *
	 * @param inventory The {@link Inventory} of the {@link Player}.
	 * @param equipment The equipment of the {@link Player}.
	 * @param inventorySlot The slot of the 2-handed item in the {@link Inventory}.
	 * @param weapon The weapon the {@link Player} currently has equipped.
	 * @param shield The shield the {@link Player} currently has equipped.
	 * @param player The {@link Player} equipping the item.
     * @param message The {@link ItemOptionMessage} sent by the client.
     */
```

**Comment by pheq** [comment]
@Major- The modifications have been done.

**Comment by Major-** [comment]
Looks good to me, needs rebasing though

**Comment by pheq** [comment]
I think it's okay now @Major-

**Comment by Major-** [comment]
It needs rebasing again, and I'm not really sure why; perhaps some of your changes are conflicting with the other people contributing to Charles' fork? I recommend that everyone contributing to apollo maintain their own unique fork for pull requests.

**Pull request merged**
