### PR TITLE
Ban and mute support, commands included.

### PR DESCRIPTION
**Pull request by lare96**
To take care of issue #76

### CODE REVIEW

**Comment by Major-** [comment]
Have you tested this thoroughly @lare96?

**Comment by Major-** [comment]
I've made some comments, can you update the code accordingly? If you commit the changes then GitHub should automatically include the new commit in this pull request.

**Comment by lare96** [comment]
`org.jruby.exceptions.RaiseException: (NoMethodError) undefined method 'nil' for # <Java::OrgApolloGameModelEntity::Player:0x15bade79>`

When trying to change on_player == null to on_player.nil

**Comment by lare96** [comment]
Also, I've tested everything but I can't test the muting itself due to issue #96 and for some reason when logging in after being banned, an unexpected response message is given rather than "your account has been disabled." This seems to happen with every response code except the "OK" one. This could be my client though, as I'm using the one you released which is apparently buggy.

**Comment by Major-** [comment]
It needs to be `nil?`, not `nil`

**Comment by lare96** [comment]
Finally figured out how to squash commits correctly, check it over and see if I missed anything

**Comment by Major-** [comment]
Nice job, thanks.

**Pull request merged**
