### PR TITLE
Refactor method add in Inventory.java

### PR DESCRIPTION
**Pull request by munggs**
Hello,
In Inventory.java, I extracted the case when the item is stackable and created a method for a better visibility in the method add.

### CODE REVIEW

**Comment by munggs** [comment]
Any thoughts about this PR ? Thanks

**Comment by Major-** [comment]
Thoughts on this @garyttierney?

**Comment by munggs** [comment]
I updated the javadoc as requested by @ryleykimmel

**Comment by ryleykimmel** [comment]
Good refactor, imo. @Major-

**Comment by munggs** [comment]
@Major- Is this ok ?

**Comment by Major-** [comment]
Yes, sorry, just needs rebasing

**Comment by munggs** [comment]
Ok, Should be ok now.
Thanks

**Comment by Major-** [comment]
Thanks!

**Pull request merged**
