### PR TITLE
Add message when encoder is equals to null

### PR DESCRIPTION
**Pull request by CharlesVaneenoo**
Hello,
I saw that decode method print a message when the decoder is null in `GameMessageDecoder`.
So I added a message when our variable encoder is null.
Thanks.

### CODE REVIEW

**Comment by garyttierney** [comment]
Hi,

Good change. Could save  wasted time debugging why some message isn't appearing on the client end. One nit pick though, you should use a `Logger` instead of printing to stdout. Besides that looks good.

Cheers.

**Comment by garyttierney** [comment]
Are there going to be any more changes to this branch?

**Comment by CharlesVaneenoo** [comment]
Not for the moment, maybe i will try to use Logger soon but i don't know when. Should I close this PR or you'll merge it like that ?

**Comment by garyttierney** [comment]
Closing for now.

**Pull request closed without merging**
