### PR TITLE
Make following and trading non-primary actions

### PR DESCRIPTION
**Pull request by lare96**
This PR makes "Follow" and "Trade with" appear **below** "Walk here" instead of being left click primary actions.

### CODE REVIEW

**Comment by rmcmk** [comment]
You should fix this in the Kotlin version of this plugin. Ruby has been phased out and will be removed soon™

**Comment by lare96** [comment]
Ahhh right, my mistake. Will do Ry!

**Comment by lare96** [comment]
Done!

**Comment by Major-** [comment]
@lare96 nice one, thanks

**Pull request closed without merging**
