### PR TITLE
Adds diagonal movement to SimplePathfindingAlgorithm class

### PR DESCRIPTION
**Pull request by DrowsySaturn**

### CODE REVIEW

**Comment by ryleykimmel** [comment]
Why do you keep closing this

**Comment by DrowsySaturn** [comment]
The first time it was because I had a typo. The second time it was because I didn't want to keep the fork in my repos. If you want the code I can send it to you @ryleykimmel

**Comment by ryleykimmel** [comment]
Put it on gist

**Comment by DrowsySaturn** [comment]
https://gist.github.com/DrowsySaturn/c551c7ee8a95bc6d4ef6 @ryleykimmel

**Pull request closed without merging**
