### PR TITLE
Added shops plugin for Kotlin

### PR DESCRIPTION
**Pull request by tlf30**
I have a rough port of the existing shops plugin in Kotlin. 
Just as in the ruby version, this only has shops for Varrock. 

This is currently untested. 

Some things had to work quite a bit different in kotlin than in ruby. I believe that this implementation is better and more flexible. But I would love some feed back. 

Thanks, 
Trevor

### CODE REVIEW

**Comment by tlf30** [comment]
When I talk to a shop owning npc I get this error on my client `Error: T2 - 206,206,71 - 88,3206,3418 - 9,19,0,28,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,
`
I do not really understand the error.

**Comment by tlf30** [comment]
So the first crash I get (above) occurs when `player.inventory.forceRefresh()` is called.  
The second crash I get is when I try to buy something: `Error: T2 - 206,206,71 - 88,3206,3418 - 9,19,0,28,83,4,-2,125,4,-1,124,4,-1,-92,4,-1,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,0,0,-128,` I do not know what server command causes this one yet.

**Comment by tlf30** [comment]
Found the problem!

**Comment by tlf30** [comment]
Buying and selling now works as far as I can tell.

**Comment by Major-** [comment]
Yeah some of the ruby code for the shops is really crap, I remember making a mental note to fix it up and then never did... thanks for the port. @garyttierney we probably want a DSL for creating shops

@tlf30 for future reference, T1 means an unrecognised opcode, T2 means something threw an Exception during frame decoding (in your case the wrong inventory id meant something in the widget handling code NPE'd, probably)

**Comment by tlf30** [comment]
@Major- thank you for the info! 

The last thing I am looking into is restocking of the shops. There was no implementation for it in the old plugin and I am having a hard time finding numbers online about it.

**Comment by tlf30** [comment]
I found the info on restocking. I have it working now.

**Comment by Major-** [comment]
So I've marked this as needs-discussion+blocked as I'd like to come up with a nice DSL for shops, and I think it probably falls to me to do that as generally the stuff underlying DSLs can make for some quite complicated kotlin. I'm going to write the DSL on top of your changes (to keep all the good stuff you converted, thanks for that) and merge it myself

**Comment by tlf30** [comment]
OK, sounds good.

**Comment by tlf30** [comment]
I have compiled together all the shops, what npcs provide them, and what items they sell. When you get the DSL done, then I will open a new PR to add them.

**Comment by Major-** [comment]
Nice, thanks. Did you compile the list yourself based on RS, or from an existing config file?

**Comment by tlf30** [comment]
I took the dataset from several servers as a base and have refined it down to only include 377 along with some tweaks. I think that it is mostly accurate at this point.

**Comment by Major-** [comment]
A recent PR moved all of the plugin locations, so there are some merge conflicts to resolve.

**Comment by tlf30** [comment]
I have rebased this

**Comment by Major-** [comment]
Finished my own work on top of this PR, will merge today. Thanks @tlf30!

**Pull request closed without merging**
