### PR TITLE
Correct typo for clay object

### PR DESCRIPTION
**Pull request by KGALLET**
Hello,

I think that the OBJECT_ID of the first clay object is incorrect.
That's why I modified it from 2180 to 2108.

Thanks

### CODE REVIEW

**Comment by Major-** [comment]
cc @WizardJesse1

**Comment by WizardJesse1** [comment]
I will double check when I can I believe they were fine

**Comment by WizardJesse1** [comment]
@Major- yes he is right there was a typo on the object id

**Comment by KGALLET** [comment]
I rebased my branch.

**Comment by Major-** [comment]
@WizardJesse1 am I merging this or are you going to include this in your mining PR?

**Comment by WizardJesse1** [comment]
@Major- i will include it in mine since i am going to double check all these objects now

**Comment by Major-** [comment]
Okay then; thanks again @KGALLET

**Pull request closed without merging**
