### PR TITLE
Fixed Magic Checks

### PR DESCRIPTION
**Pull request by WizardJesse1**
* Checks are now in order of how runescape does it.

* Changed rune to be capitalize to Rune

### CODE REVIEW

**Comment by Major-** [comment]
Can you add a space before+after the * operator on lines 70 and 104 please

LGTM once above nit addressed

**Comment by WizardJesse1** [comment]
@Major-  done

**Comment by Major-** [comment]
cc @garyttierney please merge when appropriate

**Comment by garyttierney** [comment]
@WizardJesse1 could you squash this into a single commit? If not I can do it locally later.

**Pull request closed without merging**
