### PR TITLE
New players will be queued rather than added right away.

### PR DESCRIPTION
**Pull request by lare96**
Let me know if anything needs to be changed :)

### CODE REVIEW

**Comment by Major-** [comment]
Can you reformat it to use tabs instead of spaces, and also squash those two commits into one.

**Comment by lare96** [comment]
Not sure what to do past here http://prntscr.com/8ad8pz

**Comment by Major-** [comment]
@lare96 hit Esc to exit insert mode, then :wq to save and quit

**Comment by lare96** [comment]
okay lol it seems as if it didn't remove the previous commits

**Pull request merged**
