### PR TITLE
remove a useless if found in the method GameObjectDecoder

### PR DESCRIPTION
**Pull request by CharlesVaneenoo**
Hello, 
I found a redundant if in the method so i remove it.
Thanks

### CODE REVIEW

**Comment by Major-** [comment]
Looks good, needs rebasing though

**Comment by CharlesVaneenoo** [comment]
I rebase my branch
Thanks

**Comment by Major-** [comment]
Hi there,

Merging master into your fork isn't exactly what I had in mind, because it pollutes the commit history (you can see that your PR now includes code committed by another user). A `rebase` reverts all of your commits, adds the latest changes other users have made, and applies all of your commits again on top of the changes other people made. The git book has a very good guide on doing this (and some more information about rebasing), which you can find [here](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).

Feel free to ask in IRC if you need any help with doing this

**Comment by CharlesVaneenoo** [comment]
I close this PR by removing my commit, i din't know why.
Sorry about that, i will create a new branch for this PR.

**Pull request closed without merging**
