### PR TITLE
name properly the rest of the facial emotes

### PR DESCRIPTION
**Pull request by CharlesVaneenoo**
Hello, 
I saw a TODO in emotes.rb so i had the rest of the facial emotes.

### CODE REVIEW

**Comment by WizardJesse1** [comment]
nice one

**Comment by cubeee** [comment]
evil1-3, laugh1-4, angry1-4 should be given more descriptive names

**Comment by cubeee** [comment]
These are incorrectly named and you replaced the ones that were already done, have you tested these at all?

**Comment by CharlesVaneenoo** [comment]
I remove evil1-3, laugh1-4, angry1-4 replacing by just evil, laugh and angry. I reset the ones that were already done.

**Comment by ryleykimmel** [comment]
Why would you remove evil1-3, laugh1-4, angry1-4? They are correct animations they just need named correctly.

**Comment by CharlesVaneenoo** [comment]
Alright, i will name it correctly. 
@cubeee i don't know how i can test this code (i'm a beginner in ruby)

**Comment by cubeee** [comment]
Use them in a dialogue and make sure the expressions are correct

**Comment by CharlesVaneenoo** [comment]
I've tested and corrected the emote name.

**Comment by CharlesVaneenoo** [comment]
Hello, what do you think about this pull request ? Have you got any interests on it or should i close it ? @cubeee @ryleykimmel

**Comment by garyttierney** [comment]
ping @Major- @ryleykimmel @cubeee -- needs checked by someone who knows about this.

**Comment by cubeee** [comment]
@garyttierney I'll test them all today but it would probably be easier to merge this PR now and do corrections with a new PR?

**Comment by Major-** [comment]
In agreement with @cubeee 

Sorry for taking ages to deal with this Charles, thanks for the PR

**Pull request merged**
