### PR TITLE
Manual if statement in Index.java

### PR DESCRIPTION
**Pull request by basvandriel94**
Why use an library?

### CODE REVIEW

**Comment by lare96** [comment]
Why did you remove the use of Preconditions#checkArgument for a more verbose if-statement? You also you spelled "length" wrong...

**Comment by atomicint** [comment]
@Major- ping... close...

**Comment by Hadyn** [comment]
Most of the pull requests are like this. Small additions! Gotta get on that contributer list /s

**Comment by basvandriel94** [comment]
It's just one if statement, why use Guava for this?

**Comment by Hadyn** [comment]
They are just simple helper methods to help cut down on verbose code. Either way they achieve the same purpose, I think its just a debate of preference or style. I honestly prefer your method but I see no critical issue writing it in each form. Now in terms of the pull request, if the preference is set in this fashion it's not wise to stray from that so I think it'd be wise to close this request.

**Comment by MitchZinck** [comment]
You're just committing to try and boost your ego. It doesn't add any value to the project.

/r/iamverysmart

**Comment by basvandriel94** [comment]
@Hadyn Alright, it was just my preference indeed.

@MitchZinck Wow man, chill out, i'm just here to help.. I'm also intrested in the project, so why not make some suggestions for changes?

**Comment by atomicint** [comment]
As it currently stands that is (unofficially) how the Apollo code spec deals with false conditions throughout the code-base, the reason why we use it is because it's less verbose and nicer to read in one line than your proposed 3 lines.

**Comment by Major-** [comment]
Hi, thanks for your interest. However, there are a number of good reasons for keeping Guava:
* Shorter code (as is evident from the diff of your commit).
* Reduce repeated code (your replacement would require repeating the if statement and the `new IllegalArgumentException` everywhere, with Guava we are only repeating the method call).
* It's not just used for Preconditions, but for lots of other utilities.

Also, you should check that the codebase compiles and runs before you commit something, as your original commit containing `buffer.lenght` would not have.

**Pull request closed without merging**
