### PR TITLE
Fixed food eating delays

### PR DESCRIPTION
**Pull request by WizardJesse1**
* Removed the equal check due to causing issue's with food delays since when you eat one food it should be on the same tick

### CODE REVIEW

**Comment by Major-** [comment]
I think this is okay, but unfamiliar with this behaviour.

**Comment by WizardJesse1** [comment]
@Major- i can show a video of how it use to be if you want?

**Comment by Major-** [comment]
That would be good (and ideally the new behaviour too), thanks

**Comment by WizardJesse1** [comment]
Before - http://recordit.co/DYPHeiMxfj

After - http://recordit.co/4Lzm8dsEaT

@Major-

**Comment by Major-** [comment]
Ah yeah, you're right, this new behaviour is correct. LGTM cc @garyttierney

**Pull request merged**
