### PR TITLE
creation of drink.rb

### PR DESCRIPTION
**Pull request by CharlesVaneenoo**
Hello, 
We saw a TODO with @KGALLET, so we create a new ruby class named "drink.rb". 
We separate drinks and foods between those two classes to differentiate the two types of consumable.
We are not sure about the drink sound id as we can't test the sound.
Thanks.

### CODE REVIEW

**Comment by Major-** [comment]
Needs a rebase but otherwise LGTM, thanks

**Comment by CharlesVaneenoo** [comment]
I rebase my branch and i fix a mistake by replacing the former name "food" by "drink". What do you think about that ?

**Comment by Major-** [comment]
Looks good, can you squash the commits (also, commit messages should always start with a capital letter).

**Comment by CharlesVaneenoo** [comment]
I squash my two commits, thanks for the advices @Major- i will pay attention to it now.

**Comment by Major-** [comment]
Thanks for squashing

**Pull request merged**
