### PR TITLE
Explanation of how to run the server with the client

### PR DESCRIPTION
**Pull request by AymericDu**
Hello,

I think CONTRIBUTING.md can explain how to run the server with the client. This addition allows us to save time and don't always ask the question on the IRC.

Thanks

### CODE REVIEW

**Comment by AymericDu** [comment]
I just saw the issue #280.

**Comment by WizardJesse1** [comment]
I though we did not want to contribute links to distributing the client/cache?

**Comment by garyttierney** [comment]
Hi,

This is a good addition. However, it includes links to redistributions of proprietary code and material copyrighted by Jagex and this is absolutely something we don't want to condone or encourage. 

The instructions are appreciated, but not fitting to the *Contributor Guidelines* document. I will make a repository for a wiki which is a much more fitting place.

Thanks.

**Comment by AymericDu** [comment]
I understand completely. I didn't know it was proprietary code and I recovered its links on IRC.

Sorry.

**Comment by AymericDu** [comment]
I deleted the links on my branch to not broadcast them. But the PR isn't updated with my branch. I don't know how to delete...

**Comment by garyttierney** [comment]
@AymericDu that's fine, we just don't want it upstream.

**Pull request closed without merging**
